<?php
/**
 * Created by PhpStorm.
 * User: CINTRUST
 * Date: 1/10/2019
 * Time: 1:55 PM
 */

namespace Cintrust\MadelineProto\Entities;


use Cintrust\MadelineProto\Observers\Messages\ProcessNewMessageType;

class DefaultMessage extends Entity
{
protected $observers = [ProcessNewMessageType::class];

protected function subEntities()
{
    return parent::subEntities(); // TODO: Change the autogenerated stub
}
}