<?php
/**
 * Created by Cintrust\MadelineProto\Observers\ProcessNewType.
 * @see \Cintrust\MadelineProto\Observers\ProcessNewType
 * User: Cintrust301
 * Date: Friday, 5th July, 2019
 * Time: 10:28 AM, Europe/Berlin, +02:00
 */

namespace Cintrust\MadelineProto\Entities\MessageMedia;


use Cintrust\MadelineProto\Entities\DefaultMessageMedia;
use Cintrust\MadelineProto\Entities\DefaultPhoto;
use Cintrust\MadelineProto\Entities\Photos\Photo;

/**
*Class MessageMediaPhoto
*
*
* @method Photo     getPhoto()     _description_  
*
*
*
*/
class MessageMediaPhoto extends DefaultMessageMedia
{

protected $observers =[];

protected function subEntities()
{
    return [
        'photo'=>[
            'photo'=>Photo::class,
            'default'=>DefaultPhoto::class
        ]
    ]; // TODO: Change the autogenerated stub
}

}